# Generated by Django 5.0.6 on 2024-05-24 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Be pavadinimo :)', max_length=100, verbose_name='Photo title')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Photo description')),
                ('album_photo', models.ImageField(blank=True, default='media/photos/default-photo.png', upload_to='media/photos')),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('continent', models.CharField(choices=[('as', 'Asia'), ('eu', 'Europe'), ('na', 'South America'), ('sa', 'North America'), ('af', 'Africa'), ('au', 'Australia'), ('an', 'Antarctica')], default='as', max_length=2, verbose_name='Continent')),
                ('country', models.CharField(max_length=50, verbose_name='Country')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('date', models.DateField(verbose_name='Date')),
                ('album_cover', models.ImageField(blank=True, default='media/covers/deafault-trip.jpg', upload_to='media/covers')),
            ],
            options={
                'verbose_name': 'Trip',
                'verbose_name_plural': 'Trips',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, max_length=300, null=True, verbose_name='Comment')),
                ('reaction', models.CharField(blank=True, choices=[('l', 'I love it!'), ('a', 'Aww, amazing...'), ('f', 'Looks delicious :)'), ('h', 'Hugs (& kisses)'), ('g', 'You look great ;)'), ('n', 'Sry, not my taste.'), ('w', 'Whaat?!')], default='l', max_length=1, null=True, verbose_name='Reaction')),
                ('photo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post', to='photogallery.photo')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.AddField(
            model_name='photo',
            name='trip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photo', to='photogallery.trip'),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.IntegerField(blank=True, null=True, verbose_name='Planned budget, EUR')),
                ('expense_category', models.CharField(choices=[('f', 'Flights'), ('t', 'Transport'), ('a', 'Apartment'), ('d', 'Food & Drinks'), ('e', 'Entertainments'), ('x', 'Extra - not planned')], default='f', max_length=1, verbose_name='Expenses category')),
                ('expense_amount', models.IntegerField(verbose_name='Expenses, EUR')),
                ('trip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='photogallery.trip')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
            },
        ),
    ]
