# Generated by Django 5.0.6 on 2024-05-24 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photogallery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='photo',
            new_name='post_photo',
        ),
        migrations.AlterField(
            model_name='photo',
            name='album_photo',
            field=models.ImageField(default='photos/default.jpg', upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Photo title'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='album_cover',
            field=models.ImageField(default='covers/default.jpg', upload_to='covers', verbose_name='Album cover'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='continent',
            field=models.CharField(choices=[('as', 'Asia'), ('eu', 'Europe'), ('na', 'South America'), ('sa', 'North America'), ('af', 'Africa'), ('au', 'Australia'), ('an', 'Antarctica')], default='eu', max_length=2, verbose_name='Continent'),
        ),
    ]
