# Generated by Django 5.0.6 on 2024-05-24 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photogallery', '0002_rename_photo_post_post_photo_alter_photo_album_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Smth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='smth', to='photogallery.photo')),
            ],
        ),
    ]
