# Generated by Django 5.0.6 on 2024-05-24 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photogallery', '0003_smth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smth',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='smth', to='photogallery.post'),
        ),
    ]
