# Generated by Django 5.0.6 on 2024-05-24 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photogallery', '0004_alter_smth_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='trip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post', to='photogallery.trip'),
        ),
    ]
