# Generated by Django 5.0.6 on 2024-05-24 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photogallery', '0005_post_trip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Smth',
        ),
    ]
