# Generated by Django 5.0.6 on 2024-05-24 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photogallery', '0006_delete_smth'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='reaction',
            field=models.CharField(blank=True, choices=[('l', 'I love it!'), ('a', 'Aww, amazing...'), ('f', 'Looks delicious :)'), ('h', 'Hugs (& kisses)'), ('g', 'You look great ;)'), ('n', 'Sry, not my taste.'), ('w', 'Whaat?!')], max_length=1, null=True, verbose_name='Reaction'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post', to=settings.AUTH_USER_MODEL),
        ),
    ]
