# Generated by Django 5.0.6 on 2024-05-25 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photogallery', '0010_remark_trip_remark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='remark',
        ),
        migrations.AddField(
            model_name='trip',
            name='note',
            field=models.ManyToManyField(to='photogallery.remark'),
        ),
        migrations.AlterField(
            model_name='remark',
            name='note',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Remark about the destination'),
        ),
    ]
