# Generated by Django 5.0.6 on 2024-05-25 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photogallery', '0011_remove_trip_remark_trip_note_alter_remark_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remark',
            old_name='note',
            new_name='remark',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='note',
            new_name='remark',
        ),
    ]
