# Generated by Django 5.0.6 on 2024-05-25 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photogallery', '0012_rename_note_remark_remark_rename_note_trip_remark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remark',
            old_name='remark',
            new_name='note',
        ),
    ]
