# Generated by Django 5.0.6 on 2024-05-25 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photogallery', '0013_rename_remark_remark_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='remark',
        ),
        migrations.DeleteModel(
            name='Remark',
        ),
    ]
