# Generated by Django 5.0.6 on 2024-05-25 16:00

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photogallery', '0015_alter_photo_trip_alter_post_photo_alter_post_trip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='album_cover',
            field=django_resized.forms.ResizedImageField(crop=None, default='covers/default.jpg', force_format='JPEG', keep_meta=True, quality=-1, scale=None, size=[500, 500], upload_to='covers', verbose_name='Album cover'),
        ),
    ]
