# Generated by Django 5.0.6 on 2024-05-25 18:02

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photogallery', '0018_alter_trip_album_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='album_cover',
            field=django_resized.forms.ResizedImageField(crop=None, default='covers/default.jpg', force_format='JPG', keep_meta=True, quality=-1, scale=None, size=[350, 400], upload_to='covers', verbose_name='Album cover'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='continent',
            field=models.CharField(choices=[('Asia', 'Asia'), ('Europe', 'Europe'), ('North America', 'North America'), ('South America', 'South America'), ('Africa', 'Africa'), ('Australia', 'Australia'), ('Antarctica?!', 'Antarctica')], default='Asia', max_length=20, verbose_name='Continent'),
        ),
    ]
