# Generated by Django 5.0.6 on 2024-05-25 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photogallery', '0020_alter_trip_album_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='continent',
            field=models.CharField(choices=[('Asia', 'Asia'), ('Europe', 'Europe'), ('North America', 'North America'), ('South America', 'South America'), ('Africa', 'Africa'), ('Australia', 'Australia'), ('Antarctica', 'Antarctica')], default='Asia', max_length=20, verbose_name='Continent'),
        ),
    ]
