# Generated by Django 5.0.6 on 2024-05-25 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photogallery', '0022_rename_album_cover_trip_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='cover',
            field=models.ImageField(default='covers/default.jpg', upload_to='covers'),
        ),
    ]
