# Generated by Django 5.0.6 on 2024-05-26 17:25

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photogallery', '0027_alter_trip_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='cover',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, scale=0.5, size=[350, 400], upload_to='img'),
        ),
    ]
