# Generated by Django 5.0.6 on 2024-05-26 19:16

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photogallery', '0030_alter_trip_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(default='photos/dfimg.jpg', upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='cover',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='covers/dfimg.jpg', force_format='JPEG', keep_meta=True, quality=75, scale=0.5, size=[300, 350], upload_to='covers'),
        ),
    ]
