# Generated by Django 5.0.6 on 2024-05-26 20:14

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photogallery', '0032_alter_photo_photo_alter_photo_trip_alter_post_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='photos/dfimg.jpg', force_format='JPEG', keep_meta=True, quality=100, scale=0.5, size=[1920, 1440], upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='cover',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='covers/dfimg.jpg', force_format='JPEG', keep_meta=True, quality=100, scale=0.5, size=[500, 450], upload_to='covers'),
        ),
    ]
