# Generated by Django 5.0.6 on 2024-05-26 20:23

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photogallery', '0033_alter_photo_photo_alter_trip_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='cover',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='covers/dfimg.jpg', force_format='JPEG', keep_meta=True, quality=100, scale=0.5, size=[932, 699], upload_to='covers'),
        ),
    ]
