# Generated by Django 5.0.6 on 2024-05-26 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photogallery', '0034_alter_trip_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='trip',
        ),
    ]
