# Generated by Django 5.0.6 on 2024-05-26 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photogallery', '0035_remove_post_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='trip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='photogallery.trip'),
        ),
    ]
