# Generated by Django 5.0.6 on 2024-06-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photogallery', '0039_remove_post_reaction_alter_test_name_reaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='trip',
        ),
        migrations.AddField(
            model_name='post',
            name='reaction',
            field=models.CharField(blank=True, choices=[('l', 'Love it'), ('a', 'Amazing...'), ('f', 'Delicious'), ('h', 'Hugs'), ('g', 'You look great!')], max_length=1, null=True, verbose_name='Reaction'),
        ),
        migrations.DeleteModel(
            name='Reaction',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
