# Generated by Django 5.0.6 on 2024-06-05 21:22

import django.db.models.deletion
import django_resized.forms
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photogallery', '0040_remove_test_trip_post_reaction_delete_reaction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=500, verbose_name='Theme')),
                ('theme_description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Theme description')),
            ],
            options={
                'verbose_name': 'Guest book',
                'verbose_name_plural': 'Guest book',
            },
        ),
        migrations.CreateModel(
            name='GuestPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_post', models.TextField(blank=True, max_length=300, null=True, verbose_name='Comment')),
                ('guest_picture', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=100, scale=0.5, size=[1920, 1440], upload_to='pictures')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('theme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guestposts', to='photogallery.guestbook')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guestposts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Guest post',
                'verbose_name_plural': 'Guest posts',
            },
        ),
    ]
