# Generated by Django 5.0.6 on 2024-06-05 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photogallery', '0042_rename_theme_guestpost_guestbook'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guestpost',
            old_name='guest_picture',
            new_name='picture',
        ),
        migrations.RenameField(
            model_name='guestpost',
            old_name='guest_post',
            new_name='post',
        ),
    ]
