# Generated by Django 5.0.6 on 2024-06-06 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photogallery', '0044_alter_post_reaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='reaction',
            field=models.CharField(blank=True, choices=[('Love it', 'Love it'), ('Amazing!', 'Amazing!'), ('Delicious', 'Delicious'), ('Hugs', 'Hugs'), ('You look great!', 'You look great!')], default=None, max_length=25, null=True, verbose_name='Reaction'),
        ),
    ]
