# Generated by Django 5.0.6 on 2024-05-24 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('photogallery', '0009_delete_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.IntegerField(blank=True, null=True, verbose_name='Planned budget, EUR')),
                ('expense_category', models.CharField(choices=[('f', 'Flights'), ('t', 'Transport'), ('a', 'Apartment'), ('d', 'Food & Drinks'), ('e', 'Entertainments'), ('x', 'Extra - not planned')], default='f', max_length=1, verbose_name='Expenses category')),
                ('expense_amount', models.IntegerField(verbose_name='Expenses, EUR')),
                ('trip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='photogallery.trip')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
            },
        ),
    ]
